version: '3.8'

services:

  app:
    image: mfandrade/apiblog:latest
    build: .
    restart: unless-stopped
    extra_hosts:
      - laravel.app:127.0.0.1
      - www.laravel.app:127.0.0.1
    ports:
      - 80:80
    networks:
      - localnet
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
    volumes:
      - mysqldata:/var/lib/mysql/
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    networks:
      - localnet
    restart: always

networks:
  localnet:

volumes:
  mysqldata:
