version: '3.8'

services:

  app:
    build:
      context: .
    restart: unless-stopped
    extra_hosts:
      - laravel.app:127.0.0.1
      - www.laravel.app:127.0.0.1
    ports:
      - 8000:8000
    networks:
      - localnet
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: always
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    networks:
      - localnet
    volumes:
      - mysqldata:/var/lib/mysql
      - .infra/database.sql:/docker-entrypoint-initdb.d/database.sql

networks:
  localnet:
    driver: bridge

volumes:
  mysqldata:
