version: '3.8'

services:

  app:
    build:
      context: .
    restart: unless-stopped
    extra_hosts:
      - laravel.app:127.0.0.1
      - www.laravel.app:127.0.0.1
    ports:
      - 8000:8000
    networks:
      - localnet
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - ./.infra/sql/:/docker-entrypoint-initdb.d/
      - mysqldata:/var/lib/mysql/
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    networks:
      - localnet

networks:
  localnet:
    driver: bridge

volumes:
  mysqldata:
