-- CREATE POSTS AND COMMENTS TABLES
-- ----------------------------------------------------------------------
DROP TABLE IF EXISTS posts;
CREATE TABLE posts
(
  id         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title      VARCHAR(140) NOT NULL,
  body       TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS comments;
CREATE TABLE comments
(
  id         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  text       TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  post_id    INT UNSIGNED NOT NULL,
  FOREIGN KEY (post_id)
      REFERENCES posts (id)
      ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

