DROP TABLE IF EXISTS posts;
CREATE TABLE posts
(
  id         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title      VARCHAR(140) NOT NULL,
  body       TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

DROP TABLE IF EXISTS comments;
CREATE TABLE comments
(
  id         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  text       TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  post_id    INT UNSIGNED NOT NULL,
  FOREIGN KEY (post_id)
      REFERENCES posts (id)
      ON DELETE CASCADE
) ENGINE=InnoDB;

